### ISSUE TITLE
Video captured is with segmentation even when not applied

### ISSUE THREAD

**Issue by AmbujDw** [Achilefu-Lab/cancer-goggles#22]

**Comment by AmbujDw** [comment]
Video captured is with segmentation even when threshold segmentation is not applied.

The video should be captured on real-time GUI features applied.

**Comment by AmbujDw** [comment]
Extra Detail: The Video captured has segmentation applied even when the segmentation is not applied when the video recording is started.

**Comment by wleuTietronix** [comment]
This happens with MMAL cameras, it's from old code that assumes a single MMAL will be plugged in and could be assumed as the IR sensor.

A commit was added that should respect if an MMAL stream has a threshold applied to it or not when saving to video.

**Comment by wleuTietronix** [comment]
Fixed and pushed to the migrated repo.
