### ISSUE TITLE
Sample number does not change in pictures taken

### ISSUE THREAD

**Issue by AmbujDw** [Achilefu-Lab/cancer-goggles#23]
Changing Sample number and then taking pictures does not change the sample number watermark in the pictures. It always remains the same as Sample 1.

The watermark should change when the sample number is changed by the operator.

**Comment by wleuTietronix** [comment]
The surgery phase annotation was not being changed for snapshots when changed in the carousel UI.
The surgery phase text should now update correctly in the latest push.

**Comment by wleuTietronix** [comment]
Fixed and pushed to the migrated repo.
