### ISSUE TITLE
MAINT: migrate the Tie branch to the new repo.

### ISSUE THREAD

**Issue by fangchenli** [Achilefu-Lab/cancer-goggles#26]
As we discussed in Tuesday's meeting. The Tie branch and all related issues should be migrated to the CVG-Tietronix repo.

@wleuTietronix

**Comment by wleuTietronix** [comment]
This is slated to be finished sometime this week. All HMDOpView issues except this one should already be completed (but not tested/verified), so they will be closed when migration is finished.

**Comment by wleuTietronix** [comment]
A copy of this repo was pushed to 
https://github.com/Achilefu-Lab/CVG-Tietronix
with a changed main branch and restructuring of the files.
